'use client';

import { useState, useEffect, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/AuthContext';
import ProtectedRoute from '@/components/ProtectedRoute';

// ============================================================================
// CONFIGURAÇÃO
// ============================================================================

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'https://mmusa-production.up.railway.app';

// Estados americanos
const US_STATES = [
  'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA',
  'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD',
  'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ',
  'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC',
  'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'DC'
];

// Traduções do sistema
const translations = {
  en: {
    title: '📞 Lead AI',
    subtitle: 'Lead Management & Automated Calls',
    tabs: { leads: '👥 Leads', objectives: '🎯 Objectives', prompts: '📝 Prompts', history: '📞 History', queue: '📋 Queue', settings: '⚙️ Settings' },
    stats: { total: 'Total Leads', success: 'Interested', pending: 'Pending', notInterested: 'Not Interested' },
    actions: { newLead: '+ New Lead', refresh: '🔄 Refresh', call: '📞 Call', callSelected: '📞 Call Selected', edit: '✏️', delete: '🗑️', viewHistory: '📋', addContact: '+ Contact' },
    table: { name: 'Name', phone: 'Phone', language: 'Language', status: 'Status', objective: 'Objective', contacts: 'Contacts', summary: 'AI Summary', actions: 'Actions' },
    form: {
      newLead: 'New Lead', editLead: 'Edit Lead',
      name: 'Name', phone: 'Phone', email: 'Email', notes: 'Notes',
      promptLang: 'Prompt Language', promptLangHelp: 'Language of the AI script/prompt',
      language: 'Lead Language', languageHelp: 'Language the lead speaks',
      objective: 'Call Objective', selectObjective: 'Select an objective...',
      address: 'Address',
      street: 'Street Address', city: 'City', state: 'State', zipCode: 'ZIP Code',
      aiSummary: 'AI Summary', aiSummaryHelp: 'Summary generated by AI after the call',
      cancel: 'Cancel', save: 'Save', saving: 'Saving...'
    },
    contact: {
      addTitle: 'Add Manual Contact',
      type: 'Contact Type', typeAI: 'AI Call', typeManual: 'Manual (Phone/Visit)',
      date: 'Date/Time', summary: 'Summary', outcome: 'Outcome',
      outcomes: { success: 'Success', callback: 'Callback', notInterested: 'Not Interested', noAnswer: 'No Answer', scheduled: 'Visit Scheduled' }
    },
    objectives: {
      title: 'Call Objectives',
      newObjective: '+ New Objective',
      name: 'Objective Name', description: 'Description / AI Instructions',
      descriptionHelp: 'Detailed instructions for the AI during the call',
      examples: 'Examples: Needs Assessment, Customer Recovery, Price Follow-up, Schedule Visit',
      noObjectives: 'No objectives registered. Click "+ New Objective" to create.',
      confirmDelete: 'Delete this objective?',
      editObjective: 'Edit Objective'
    },
    history: { title: 'Contact History', selectLead: 'Select a lead to view history', aiCall: '🤖 AI Call', manual: '👤 Manual', duration: 'Duration', intent: 'Intent', context: 'Context', transcript: 'Transcript', noHistory: 'No contacts recorded', outcome: 'Outcome', summary: 'Summary' },
    queue: { title: 'Call Queue', inProgress: '🔄 In Progress', stopped: '⏸️ Stopped', calling: 'Calling', pending: 'pending', cancel: '🛑 Cancel Queue', results: 'Results', completed: 'completed' },
    prompts: { title: 'AI Prompts', type: 'Type', systemPrompt: 'System Prompt', greeting: 'Greeting', save: 'Save Prompt', reload: '🔄 Reload', nameVar: 'Use {name} to include the lead name dynamically', selectLang: 'Select language to edit' },
    settings: { title: 'Settings', companyName: 'Company Name', companyNameHelp: 'This name will be used by the AI when introducing itself', saved: 'Settings saved!' },
    status: { new: 'New', contacted: 'Contacted', interested: 'Interested', notInterested: 'Not Interested', scheduled: 'Scheduled', converted: 'Converted' },
    messages: { leadCreated: 'Lead created!', leadUpdated: 'Lead updated!', leadDeleted: 'Lead deleted!', callStarted: 'Call started!', queueStarted: 'Queue started!', queueCancelled: 'Queue cancelled!', promptSaved: 'Prompt saved!', contactAdded: 'Contact added!', selectAtLeastOne: 'Select at least one lead', errorLoading: 'Error loading', objectiveCreated: 'Objective created!', objectiveDeleted: 'Objective deleted!', objectiveUpdated: 'Objective updated!' },
    noLeads: 'No leads registered. Click "+ New Lead" to start.',
    languages: { en: '🇺🇸 English', es: '🇪🇸 Spanish', pt: '🇧🇷 Portuguese' },
    filters: { all: 'All', filterByStatus: 'Filter by status' }
  },
  pt: {
    title: '📞 Lead AI',
    subtitle: 'Gestão de Leads e Chamadas Automatizadas',
    tabs: { leads: '👥 Leads', objectives: '🎯 Objetivos', prompts: '📝 Prompts', history: '📞 Histórico', queue: '📋 Fila', settings: '⚙️ Config' },
    stats: { total: 'Total de Leads', success: 'Interessados', pending: 'Pendentes', notInterested: 'Não Interessados' },
    actions: { newLead: '+ Novo Lead', refresh: '🔄 Atualizar', call: '📞 Ligar', callSelected: '📞 Ligar Selecionados', edit: '✏️', delete: '🗑️', viewHistory: '📋', addContact: '+ Contato' },
    table: { name: 'Nome', phone: 'Telefone', language: 'Idioma', status: 'Status', objective: 'Objetivo', contacts: 'Contatos', summary: 'Resumo IA', actions: 'Ações' },
    form: {
      newLead: 'Novo Lead', editLead: 'Editar Lead',
      name: 'Nome', phone: 'Telefone', email: 'Email', notes: 'Notas',
      promptLang: 'Idioma do Prompt', promptLangHelp: 'Idioma do script/prompt da IA',
      language: 'Idioma do Lead', languageHelp: 'Idioma que o lead fala',
      objective: 'Objetivo da Ligação', selectObjective: 'Selecione um objetivo...',
      address: 'Endereço',
      street: 'Endereço', city: 'Cidade', state: 'Estado', zipCode: 'ZIP Code',
      aiSummary: 'Resumo da IA', aiSummaryHelp: 'Resumo gerado pela IA após a ligação',
      cancel: 'Cancelar', save: 'Salvar', saving: 'Salvando...'
    },
    contact: {
      addTitle: 'Adicionar Contato Manual',
      type: 'Tipo de Contato', typeAI: 'Ligação IA', typeManual: 'Manual (Telefone/Visita)',
      date: 'Data/Hora', summary: 'Resumo', outcome: 'Resultado',
      outcomes: { success: 'Sucesso', callback: 'Retornar', notInterested: 'Não Interessado', noAnswer: 'Não Atendeu', scheduled: 'Visita Agendada' }
    },
    objectives: {
      title: 'Objetivos de Ligação',
      newObjective: '+ Novo Objetivo',
      name: 'Nome do Objetivo', description: 'Descrição / Instruções para IA',
      descriptionHelp: 'Instruções detalhadas para a IA durante a ligação',
      examples: 'Exemplos: Levantamento de Necessidade, Recuperação de Cliente, Follow-up de Preço, Agendar Visita',
      noObjectives: 'Nenhum objetivo cadastrado. Clique em "+ Novo Objetivo" para criar.',
      confirmDelete: 'Excluir este objetivo?',
      editObjective: 'Editar Objetivo'
    },
    history: { title: 'Histórico de Contatos', selectLead: 'Selecione um lead para ver o histórico', aiCall: '🤖 Ligação IA', manual: '👤 Manual', duration: 'Duração', intent: 'Intenção', context: 'Contexto', transcript: 'Transcrição', noHistory: 'Nenhum contato registrado', outcome: 'Resultado', summary: 'Resumo' },
    queue: { title: 'Fila de Chamadas', inProgress: '🔄 Em andamento', stopped: '⏸️ Parada', calling: 'Ligando para', pending: 'pendentes', cancel: '🛑 Cancelar Fila', results: 'Resultados', completed: 'completas' },
    prompts: { title: 'Prompts da IA', type: 'Tipo', systemPrompt: 'System Prompt', greeting: 'Saudação', save: 'Salvar Prompt', reload: '🔄 Recarregar', nameVar: 'Use {name} para incluir o nome do lead dinamicamente', selectLang: 'Selecione o idioma para editar' },
    settings: { title: 'Configurações', companyName: 'Nome da Empresa', companyNameHelp: 'Este nome será usado pela IA ao se apresentar', saved: 'Configurações salvas!' },
    status: { new: 'Novo', contacted: 'Contatado', interested: 'Interessado', notInterested: 'Não Interessado', scheduled: 'Agendado', converted: 'Convertido' },
    messages: { leadCreated: 'Lead criado!', leadUpdated: 'Lead atualizado!', leadDeleted: 'Lead excluído!', callStarted: 'Chamada iniciada!', queueStarted: 'Fila iniciada!', queueCancelled: 'Fila cancelada!', promptSaved: 'Prompt salvo!', contactAdded: 'Contato adicionado!', selectAtLeastOne: 'Selecione pelo menos um lead', errorLoading: 'Erro ao carregar', objectiveCreated: 'Objetivo criado!', objectiveDeleted: 'Objetivo excluído!', objectiveUpdated: 'Objetivo atualizado!' },
    noLeads: 'Nenhum lead cadastrado. Clique em "+ Novo Lead" para começar.',
    languages: { en: '🇺🇸 Inglês', es: '🇪🇸 Espanhol', pt: '🇧🇷 Português' },
    filters: { all: 'Todos', filterByStatus: 'Filtrar por status' }
  }
};

// ============================================================================
// COMPONENTE PRINCIPAL
// ============================================================================

function DashboardContent() {
  const router = useRouter();
  const { user, userProfile, logout } = useAuth();
  // Idioma do sistema (interface)
  const [systemLang, setSystemLang] = useState('en');
  const t = translations[systemLang];
  
  // Estado geral
  const [activeTab, setActiveTab] = useState('leads');
  const [leads, setLeads] = useState([]);
  const [objectives, setObjectives] = useState([]);
  const [selectedLeads, setSelectedLeads] = useState(new Set());
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(null);

  // Verificação de setup
  const [isCheckingSetup, setIsCheckingSetup] = useState(true);
  
  // Menu do usuário
  const [showUserMenu, setShowUserMenu] = useState(false);
  
  // Filtros
  const [statusFilter, setStatusFilter] = useState('all');
  
  // Configurações
  const [companyName, setCompanyName] = useState('');
  
  // Form de lead - TODOS OS CAMPOS
  const [showForm, setShowForm] = useState(false);
  const [editingLead, setEditingLead] = useState(null);
  const [formData, setFormData] = useState({
    name: '',
    phone: '',
    email: '',
    // Endereço padrão americano
    street: '',
    city: '',
    state: '',
    zipCode: '',
    // Chaveamentos de idioma
    promptLang: 'en',    // Idioma do PROMPT (script da IA)
    language: 'en',       // Idioma do LEAD (que ele fala)
    // Objetivo
    objectiveId: '',
    // Resumo da IA
    aiSummary: '',
    // Outros
    notes: '',
    status: 'new'
  });
  const [phoneCountry, setPhoneCountry] = useState('us');
  
  // Form de objetivo
  const [showObjectiveForm, setShowObjectiveForm] = useState(false);
  const [editingObjective, setEditingObjective] = useState(null);
  const [objectiveFormData, setObjectiveFormData] = useState({ name: '', description: '' });
  
  // Form de contato manual
  const [showContactForm, setShowContactForm] = useState(false);
  const [contactFormLead, setContactFormLead] = useState(null);
  const [contactData, setContactData] = useState({
    type: 'manual', date: '', summary: '', outcome: 'success'
  });
  
  // Fila de chamadas
  const [queueStatus, setQueueStatus] = useState(null);
  
  // Prompts
  const [prompts, setPrompts] = useState(null);
  const [editingPromptType, setEditingPromptType] = useState('system');
  const [editingPromptLang, setEditingPromptLang] = useState('en');
  const [promptText, setPromptText] = useState('');
  
  // Histórico
  const [selectedLeadForHistory, setSelectedLeadForHistory] = useState(null);
  const [leadHistory, setLeadHistory] = useState([]);

  // ============================================================================
  // OBJETIVOS - GERENCIAMENTO LOCAL + API
  // ============================================================================
  
  const loadObjectives = useCallback(() => {
    try {
      const saved = localStorage.getItem('leadai_objectives');
      if (saved) {
        const parsed = JSON.parse(saved);
        setObjectives(parsed);
        return parsed;
      }
    } catch (e) {
      console.error('Error loading objectives:', e);
    }
    return [];
  }, []);
  
  const saveObjectives = useCallback((newObjectives) => {
    try {
      localStorage.setItem('leadai_objectives', JSON.stringify(newObjectives));
      setObjectives(newObjectives);
    } catch (e) {
      console.error('Error saving objectives:', e);
    }
  }, []);

  // ============================================================================
  // API
  // ============================================================================
  
  const fetchLeads = useCallback(async () => {
    try {
      setLoading(true);
      const res = await fetch(`${API_URL}/api/leads`);
      const data = await res.json();
      if (data.leads) setLeads(data.leads);
    } catch (err) {
      setError(t.messages.errorLoading + ': ' + err.message);
    } finally {
      setLoading(false);
    }
  }, [t.messages.errorLoading]);
  
  const fetchSettings = useCallback(async () => {
    try {
      const res = await fetch(`${API_URL}/api/settings`);
      const data = await res.json();
      if (data.companyName) setCompanyName(data.companyName);
    } catch (err) {
      const saved = localStorage.getItem('leadai_companyName');
      if (saved) setCompanyName(saved);
    }
  }, []);
  
  const fetchQueueStatus = useCallback(async () => {
    try {
      const res = await fetch(`${API_URL}/api/call/queue`);
      const data = await res.json();
      setQueueStatus(data);
    } catch (err) {
      console.error('Queue error:', err);
    }
  }, []);
  
  const fetchPrompts = useCallback(async () => {
    try {
      const res = await fetch(`${API_URL}/api/prompts`);
      const data = await res.json();
      setPrompts(data);
    } catch (err) {
      setError(t.messages.errorLoading + ': prompts');
    }
  }, [t.messages.errorLoading]);
  
  const fetchLeadHistory = useCallback(async (leadId) => {
    try {
      setLoading(true);
      const res = await fetch(`${API_URL}/api/leads/${leadId}/calls`);
      const data = await res.json();
      
      // Buscar também contatos manuais do localStorage
      let manualContacts = [];
      try {
        const saved = localStorage.getItem(`leadai_contacts_${leadId}`);
        if (saved) manualContacts = JSON.parse(saved);
      } catch (e) {
        console.error('Error loading manual contacts:', e);
      }
      
      // Combinar e ordenar por data
      const allContacts = [
        ...(data.calls || []).map(c => ({ ...c, contactType: 'ai' })),
        ...manualContacts.map(c => ({ ...c, contactType: 'manual' }))
      ].sort((a, b) => {
        const dateA = a.startedAt?._seconds || new Date(a.startedAt || a.date || 0).getTime() / 1000;
        const dateB = b.startedAt?._seconds || new Date(b.startedAt || b.date || 0).getTime() / 1000;
        return dateB - dateA;
      });
      
      setLeadHistory(allContacts);
    } catch (err) {
      setError(t.messages.errorLoading + ': history');
    } finally {
      setLoading(false);
    }
  }, [t.messages.errorLoading]);

  // ============================================================================
  // EFFECTS
  // ============================================================================
  
  useEffect(() => {
    if (!isCheckingSetup) {
      fetchLeads();
      loadObjectives();
      fetchSettings();
      fetchQueueStatus();
      const interval = setInterval(fetchQueueStatus, 3000);
      return () => clearInterval(interval);
    }
  }, [isCheckingSetup, fetchLeads, loadObjectives, fetchSettings, fetchQueueStatus]);
  
  useEffect(() => {
    if (activeTab === 'prompts') fetchPrompts();
  }, [activeTab, fetchPrompts]);
  
  useEffect(() => {
    if (prompts && editingPromptType && editingPromptLang) {
      const text = editingPromptType === 'system' 
        ? prompts.active?.systemPrompts?.[editingPromptLang]
        : prompts.active?.greetingInstructions?.[editingPromptLang];
      setPromptText(text || '');
    }
  }, [prompts, editingPromptType, editingPromptLang]);

    useEffect(() => {
    const checkSetup = async () => {
      try {
        const response = await fetch(`${API_URL}/api/setup`);
        const result = await response.json();
        
        if (!result.isConfigured) {
          // Setup não feito, redirecionar
          router.push('/setup');
          return;
        }
        
        // Setup OK, carregar nome da empresa
        if (result.data?.companyName) {
          setCompanyName(result.data.companyName);
        }
        
        setIsCheckingSetup(false);
      } catch (error) {
        console.error('Error checking setup:', error);
        setIsCheckingSetup(false);
      }
    };
    
    checkSetup();
  }, [router]);

  // ============================================================================
  // HANDLERS - LEADS
  // ============================================================================
  
  const handleSaveLead = async () => {
    try {
      setLoading(true);
      setError(null);
      
      // Formatar telefone
      let formattedPhone = formData.phone.replace(/\D/g, '');
      formattedPhone = phoneCountry === 'us' ? '+1' + formattedPhone : '+55' + formattedPhone;
      
      // Buscar objetivo selecionado
      const selectedObjective = objectives.find(o => o.id === formData.objectiveId);
      
      // Preparar dados completos para o Firebase
      const leadData = {
        name: formData.name,
        phone: formattedPhone,
        email: formData.email || '',
        // Endereço
        street: formData.street || '',
        city: formData.city || '',
        state: formData.state || '',
        zipCode: formData.zipCode || '',
        // Chaveamentos de idioma
        promptLang: formData.promptLang || 'en',
        language: formData.language || 'en',
        // Objetivo
        objectiveId: formData.objectiveId || '',
        objectiveName: selectedObjective?.name || '',
        callContext: selectedObjective?.description || '',
        // Resumo da IA
        aiSummary: formData.aiSummary || '',
        // Outros
        notes: formData.notes || '',
        status: formData.status || 'new',
        // Timestamps
        updatedAt: new Date().toISOString()
      };
      
      // Se for novo lead, adicionar createdAt
      if (!editingLead) {
        leadData.createdAt = new Date().toISOString();
        leadData.totalCalls = 0;
      }
      
      const url = editingLead ? `${API_URL}/api/leads/${editingLead.id}` : `${API_URL}/api/leads`;
      const method = editingLead ? 'PUT' : 'POST';
      
      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(leadData)
      });
      
      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.error || 'Error saving lead');
      }
      
      setSuccess(editingLead ? t.messages.leadUpdated : t.messages.leadCreated);
      closeForm();
      fetchLeads();
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };
  
  const handleDeleteLead = async (leadId) => {
    if (!confirm('Delete this lead?')) return;
    try {
      setLoading(true);
      await fetch(`${API_URL}/api/leads/${leadId}`, { method: 'DELETE' });
      setSuccess(t.messages.leadDeleted);
      fetchLeads();
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };
  
  const handleEditLead = (lead) => {
    setEditingLead(lead);
    let phone = lead.phone || '';
    let country = 'us';
    if (phone.startsWith('+55')) { country = 'br'; phone = phone.substring(3); }
    else if (phone.startsWith('+1')) { country = 'us'; phone = phone.substring(2); }
    setPhoneCountry(country);
    setFormData({
      name: lead.name || '',
      phone,
      email: lead.email || '',
      street: lead.street || '',
      city: lead.city || '',
      state: lead.state || '',
      zipCode: lead.zipCode || '',
      promptLang: lead.promptLang || 'en',
      language: lead.language || 'en',
      objectiveId: lead.objectiveId || '',
      aiSummary: lead.aiSummary || '',
      notes: lead.notes || '',
      status: lead.status || 'new'
    });
    setShowForm(true);
  };
  
  const handleQuickStatusChange = async (leadId, newStatus) => {
    try {
      // Atualizar estado local IMEDIATAMENTE para feedback visual
      setLeads(prevLeads => 
        prevLeads.map(lead => 
          lead.id === leadId ? { ...lead, status: newStatus } : lead
        )
      );
      
      // Enviar para API
      const res = await fetch(`${API_URL}/api/leads/${leadId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: newStatus, updatedAt: new Date().toISOString() })
      });
      
      if (!res.ok) {
        throw new Error('Failed to update status');
      }
    } catch (err) {
      setError(err.message);
      // Reverter em caso de erro - recarregar dados
      fetchLeads();
    }
  };
  
  const handleCallSingle = async (lead) => {
    try {
      setLoading(true);
      const selectedObjective = objectives.find(o => o.id === lead.objectiveId);
      
      const res = await fetch(`${API_URL}/api/call`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          leadId: lead.id,
          phone: lead.phone,
          leadName: lead.name,
          // Usar promptLang para o idioma do prompt
          lang: lead.promptLang || 'en',
          // Passar também o idioma do lead para referência
          leadLanguage: lead.language || 'en',
          callContext: selectedObjective?.description || lead.callContext || '',
          companyName: companyName
        })
      });
      const data = await res.json();
      if (res.ok) setSuccess(t.messages.callStarted + ' ' + lead.name);
      else throw new Error(data.error);
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };
  
  const handleCallBatch = async () => {
    if (selectedLeads.size === 0) {
      setError(t.messages.selectAtLeastOne);
      return;
    }
    const leadsToCall = leads.filter(l => selectedLeads.has(l.id));
    try {
      setLoading(true);
      const res = await fetch(`${API_URL}/api/call/batch`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          leads: leadsToCall.map(l => {
            const obj = objectives.find(o => o.id === l.objectiveId);
            return {
              leadId: l.id,
              leadName: l.name,
              phone: l.phone,
              lang: l.promptLang || 'en',
              leadLanguage: l.language || 'en',
              callContext: obj?.description || l.callContext || '',
              companyName: companyName
            };
          })
        })
      });
      const data = await res.json();
      if (res.ok) {
        setSuccess(t.messages.queueStarted + ` (${leadsToCall.length})`);
        setSelectedLeads(new Set());
        setActiveTab('queue');
      } else throw new Error(data.error);
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };
  
  const handleCancelQueue = async () => {
    try {
      await fetch(`${API_URL}/api/call/queue`, { method: 'DELETE' });
      setSuccess(t.messages.queueCancelled);
      fetchQueueStatus();
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError(err.message);
    }
  };

  // ============================================================================
  // HANDLERS - OBJETIVOS
  // ============================================================================
  
  const handleSaveObjective = () => {
    try {
      if (!objectiveFormData.name || !objectiveFormData.description) {
        setError('Name and description are required');
        return;
      }
      
      let updatedObjectives;
      
      if (editingObjective) {
        // Editar existente
        updatedObjectives = objectives.map(obj => 
          obj.id === editingObjective.id 
            ? { ...obj, name: objectiveFormData.name, description: objectiveFormData.description, updatedAt: new Date().toISOString() }
            : obj
        );
        setSuccess(t.messages.objectiveUpdated);
      } else {
        // Criar novo
        const newObjective = {
          id: 'obj_' + Date.now(),
          name: objectiveFormData.name,
          description: objectiveFormData.description,
          createdAt: new Date().toISOString()
        };
        updatedObjectives = [...objectives, newObjective];
        setSuccess(t.messages.objectiveCreated);
      }
      
      saveObjectives(updatedObjectives);
      setShowObjectiveForm(false);
      setEditingObjective(null);
      setObjectiveFormData({ name: '', description: '' });
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError(err.message);
    }
  };
  
  const handleEditObjective = (obj) => {
    setEditingObjective(obj);
    setObjectiveFormData({ name: obj.name, description: obj.description });
    setShowObjectiveForm(true);
  };
  
  const handleDeleteObjective = (objId) => {
    if (!confirm(t.objectives.confirmDelete)) return;
    try {
      const updatedObjectives = objectives.filter(o => o.id !== objId);
      saveObjectives(updatedObjectives);
      setSuccess(t.messages.objectiveDeleted);
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError(err.message);
    }
  };

  // ============================================================================
  // HANDLERS - PROMPTS
  // ============================================================================
  
  const handleSavePrompt = async () => {
    try {
      setLoading(true);
      const endpoint = editingPromptType === 'system' ? 'system' : 'greeting';
      const res = await fetch(`${API_URL}/api/prompts/${endpoint}/${editingPromptLang}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: promptText })
      });
      if (!res.ok) throw new Error('Error saving prompt');
      setSuccess(t.messages.promptSaved);
      fetchPrompts();
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  // ============================================================================
  // HANDLERS - CONTATOS MANUAIS
  // ============================================================================
  
  const handleAddContact = async () => {
    if (!contactFormLead) return;
    try {
      setLoading(true);
      
      const newContact = {
        id: 'manual_' + Date.now(),
        contactType: 'manual',
        date: contactData.date || new Date().toISOString(),
        summary: contactData.summary,
        outcome: contactData.outcome,
        createdAt: new Date().toISOString()
      };
      
      // Salvar no localStorage
      const key = `leadai_contacts_${contactFormLead.id}`;
      const existing = JSON.parse(localStorage.getItem(key) || '[]');
      localStorage.setItem(key, JSON.stringify([...existing, newContact]));
      
      // Atualizar lead no Firebase
      await fetch(`${API_URL}/api/leads/${contactFormLead.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          lastContactDate: new Date().toISOString(),
          totalCalls: (contactFormLead.totalCalls || 0) + 1,
          updatedAt: new Date().toISOString()
        })
      });
      
      setSuccess(t.messages.contactAdded);
      setShowContactForm(false);
      setContactFormLead(null);
      setContactData({ type: 'manual', date: '', summary: '', outcome: 'success' });
      fetchLeads();
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  // ============================================================================
  // HANDLERS - SETTINGS
  // ============================================================================
  
  const handleSaveSettings = async () => {
    try {
      setLoading(true);
      
      // Salvar localmente sempre
      localStorage.setItem('leadai_companyName', companyName);
      
      // Tentar salvar na API
      try {
        await fetch(`${API_URL}/api/settings`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ companyName })
        });
      } catch (e) {
        console.log('API settings not available, saved locally');
      }
      
      setSuccess(t.settings.saved);
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  // ============================================================================
  // HANDLERS - AUTH
  // ============================================================================
  
  const handleLogout = async () => {
    await logout();
    router.push('/login');
  };

  // ============================================================================
  // HELPERS
  // ============================================================================
  
  const closeForm = () => {
    setShowForm(false);
    setEditingLead(null);
    setFormData({
      name: '', phone: '', email: '',
      street: '', city: '', state: '', zipCode: '',
      promptLang: 'en', language: 'en',
      objectiveId: '', aiSummary: '', notes: '', status: 'new'
    });
    setPhoneCountry('us');
  };
  
  const closeObjectiveForm = () => {
    setShowObjectiveForm(false);
    setEditingObjective(null);
    setObjectiveFormData({ name: '', description: '' });
  };
  
  const toggleSelectLead = (id) => {
    const newSet = new Set(selectedLeads);
    newSet.has(id) ? newSet.delete(id) : newSet.add(id);
    setSelectedLeads(newSet);
  };
  
  const toggleSelectAll = () => {
    const filtered = filteredLeads;
    setSelectedLeads(selectedLeads.size === filtered.length ? new Set() : new Set(filtered.map(l => l.id)));
  };
  
  const handleViewHistory = (lead) => {
    setSelectedLeadForHistory(lead);
    fetchLeadHistory(lead.id);
    setActiveTab('history');
  };
  
  const formatDate = (ts) => {
    if (!ts) return 'N/A';
    try {
      if (ts.toDate) return ts.toDate().toLocaleString(systemLang === 'pt' ? 'pt-BR' : 'en-US');
      if (ts._seconds) return new Date(ts._seconds * 1000).toLocaleString(systemLang === 'pt' ? 'pt-BR' : 'en-US');
      return new Date(ts).toLocaleString(systemLang === 'pt' ? 'pt-BR' : 'en-US');
    } catch { return 'N/A'; }
  };

  // ============================================================================
  // FILTROS E ESTATÍSTICAS
  // ============================================================================
  
  const filteredLeads = statusFilter === 'all' 
    ? leads 
    : leads.filter(l => {
        if (statusFilter === 'interested') return l.status === 'interested' || l.lastIntent === 'purchase';
        if (statusFilter === 'pending') return !l.status || l.status === 'new' || l.status === 'contacted';
        if (statusFilter === 'notInterested') return l.status === 'notInterested' || l.lastIntent === 'not_interested';
        return l.status === statusFilter;
      });
  
  const stats = {
    total: leads.length,
    interested: leads.filter(l => l.status === 'interested' || l.lastIntent === 'purchase').length,
    pending: leads.filter(l => !l.status || l.status === 'new' || l.status === 'contacted').length,
    notInterested: leads.filter(l => l.status === 'notInterested' || l.lastIntent === 'not_interested').length
  };
  
  const getStatusColor = (status) => {
    const colors = {
      new: 'bg-gray-600', contacted: 'bg-blue-600', interested: 'bg-green-600',
      notInterested: 'bg-red-600', scheduled: 'bg-yellow-600', converted: 'bg-purple-600'
    };
    return colors[status] || 'bg-gray-600';
  };
  
  const getIntentColor = (intent) => {
    const colors = { purchase: 'bg-green-600', interested: 'bg-green-500', not_interested: 'bg-red-600', callback: 'bg-yellow-600' };
    return colors[intent] || 'bg-gray-600';
  };
  
  const getOutcomeLabel = (outcome) => {
    return t.contact.outcomes[outcome] || outcome;
  };


// User info
  const displayName = userProfile?.displayName || user?.displayName || user?.email?.split('@')[0] || 'User';
  const initials = displayName.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2);


  // ============================================================================
  // RENDER
  // ============================================================================
  
  return (
    <div className="min-h-screen bg-gray-900 text-white">
    {/* ===== HEADER COM MENU DE USUÁRIO ===== */}
      <header className="bg-gray-800 border-b border-gray-700 p-4">
        <div className="max-w-7xl mx-auto flex flex-wrap justify-between items-center gap-4">
          <div>
            <h1 className="text-2xl font-bold text-blue-400">{t.title}</h1>
            <p className="text-sm text-gray-400">{t.subtitle}</p>
          </div>
          
          <div className="flex items-center gap-4">
            {/* Idioma do Sistema */}
            <select
              value={systemLang}
              onChange={(e) => setSystemLang(e.target.value)}
              className="bg-gray-700 border border-gray-600 rounded px-3 py-2 text-sm"
            >
              <option value="en">🇺🇸 English</option>
              <option value="pt">🇧🇷 Português</option>
            </select>
            
            {/* Status da Fila */}
            {queueStatus?.isProcessing && (
              <div className="bg-yellow-600 px-4 py-2 rounded-lg flex items-center gap-2">
                <div className="animate-pulse w-3 h-3 bg-white rounded-full"></div>
                <span>{t.queue.calling}: {queueStatus.current?.leadName}</span>
              </div>
            )}
            
            {/* Menu do Usuário */}
            <div className="relative">
              <button
                onClick={() => setShowUserMenu(!showUserMenu)}
                className="flex items-center gap-3 bg-gray-700 hover:bg-gray-600 rounded-xl px-4 py-2 transition-colors"
              >
                {user?.photoURL ? (
                  <img 
                    src={user.photoURL} 
                    alt={displayName}
                    className="w-8 h-8 rounded-full"
                  />
                ) : (
                  <div className="w-8 h-8 bg-blue-600 rounded-full flex items-center justify-center text-sm font-medium">
                    {initials}
                  </div>
                )}
                <span className="text-sm font-medium hidden sm:block">{displayName}</span>
                <svg className={`w-4 h-4 text-gray-400 transition-transform ${showUserMenu ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                </svg>
              </button>
              
              {/* Dropdown Menu */}
              {showUserMenu && (
                <>
                  <div 
                    className="fixed inset-0 z-10" 
                    onClick={() => setShowUserMenu(false)}
                  />
                  <div className="absolute right-0 top-full mt-2 w-48 bg-gray-800 border border-gray-700 rounded-xl shadow-xl z-20 overflow-hidden">
                    <div className="px-4 py-3 border-b border-gray-700">
                      <p className="text-sm font-medium truncate">{displayName}</p>
                      <p className="text-xs text-gray-400 truncate">{user?.email}</p>
                    </div>
                    <div className="py-1">
                      <button
                        onClick={() => {
                          setShowUserMenu(false);
                          setActiveTab('settings');
                        }}
                        className="w-full px-4 py-2 text-left text-sm text-gray-300 hover:bg-gray-700 transition-colors flex items-center gap-2"
                      >
                        <span>⚙️</span> Settings
                      </button>
                      <button
                        onClick={() => {
                          setShowUserMenu(false);
                          router.push('/setup?new_prompt=true');
                        }}
                        className="w-full px-4 py-2 text-left text-sm text-gray-300 hover:bg-gray-700 transition-colors flex items-center gap-2"
                      >
                        <span>🎯</span> New Prompt
                      </button>
                      <button
                        onClick={handleLogout}
                        className="w-full px-4 py-2 text-left text-sm text-red-400 hover:bg-gray-700 transition-colors flex items-center gap-2"
                      >
                        <span>🚪</span> Sign Out
                      </button>
                    </div>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      </header>
      
      {/* ===== ALERTS ===== */}
      {error && (
        <div className="max-w-7xl mx-auto mt-4 px-4">
          <div className="bg-red-600 p-3 rounded-lg flex justify-between">
            <span>{error}</span>
            <button onClick={() => setError(null)}>✕</button>
          </div>
        </div>
      )}
      {success && (
        <div className="max-w-7xl mx-auto mt-4 px-4">
          <div className="bg-green-600 p-3 rounded-lg flex justify-between">
            <span>{success}</span>
            <button onClick={() => setSuccess(null)}>✕</button>
          </div>
        </div>
      )}
      
      {/* ===== TABS ===== */}
      <nav className="bg-gray-800 border-b border-gray-700">
        <div className="max-w-7xl mx-auto px-4 flex gap-1 overflow-x-auto">
          {['leads', 'objectives', 'prompts', 'history', 'queue', 'settings'].map(tab => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-3 font-medium whitespace-nowrap ${activeTab === tab ? 'bg-blue-600' : 'text-gray-400 hover:bg-gray-700'}`}
            >
              {t.tabs[tab]}
              {tab === 'leads' && leads.length > 0 && <span className="ml-2 bg-gray-600 px-2 py-0.5 rounded-full text-xs">{leads.length}</span>}
              {tab === 'objectives' && objectives.length > 0 && <span className="ml-2 bg-cyan-600 px-2 py-0.5 rounded-full text-xs">{objectives.length}</span>}
              {tab === 'queue' && queueStatus?.pending > 0 && <span className="ml-2 bg-yellow-600 px-2 py-0.5 rounded-full text-xs">{queueStatus.pending}</span>}
            </button>
          ))}
        </div>
      </nav>
      
      {/* ===== CONTENT ===== */}
      <main className="max-w-7xl mx-auto p-4">
        
        {/* ==================== LEADS TAB ==================== */}
        {activeTab === 'leads' && (
          <div>
            {/* Stats Cards com Filtros */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
              <div 
                className={`bg-gray-800 rounded-xl p-4 border-l-4 border-blue-500 cursor-pointer transition ${statusFilter === 'all' ? 'ring-2 ring-blue-500' : 'hover:bg-gray-750'}`}
                onClick={() => setStatusFilter('all')}
              >
                <div className="text-3xl font-bold">{stats.total}</div>
                <div className="text-gray-400 text-sm">{t.stats.total}</div>
              </div>
              
              <div 
                className={`bg-gray-800 rounded-xl p-4 border-l-4 border-green-500 cursor-pointer transition ${statusFilter === 'interested' ? 'ring-2 ring-green-500' : 'hover:bg-gray-750'}`}
                onClick={() => setStatusFilter('interested')}
              >
                <div className="text-3xl font-bold text-green-400">{stats.interested}</div>
                <div className="text-gray-400 text-sm">{t.stats.success}</div>
              </div>
              
              <div 
                className={`bg-gray-800 rounded-xl p-4 border-l-4 border-yellow-500 cursor-pointer transition ${statusFilter === 'pending' ? 'ring-2 ring-yellow-500' : 'hover:bg-gray-750'}`}
                onClick={() => setStatusFilter('pending')}
              >
                <div className="text-3xl font-bold text-yellow-400">{stats.pending}</div>
                <div className="text-gray-400 text-sm">{t.stats.pending}</div>
              </div>
              
              <div 
                className={`bg-gray-800 rounded-xl p-4 border-l-4 border-red-500 cursor-pointer transition ${statusFilter === 'notInterested' ? 'ring-2 ring-red-500' : 'hover:bg-gray-750'}`}
                onClick={() => setStatusFilter('notInterested')}
              >
                <div className="text-3xl font-bold text-red-400">{stats.notInterested}</div>
                <div className="text-gray-400 text-sm">{t.stats.notInterested}</div>
              </div>
            </div>
            
            {/* Actions */}
            <div className="flex flex-wrap gap-4 mb-6 items-center">
              <button onClick={() => { setShowForm(true); setEditingLead(null); }} className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg font-medium">
                {t.actions.newLead}
              </button>
              {selectedLeads.size > 0 && (
                <button onClick={handleCallBatch} disabled={loading} className="bg-green-600 hover:bg-green-700 px-4 py-2 rounded-lg font-medium">
                  {t.actions.callSelected} ({selectedLeads.size})
                </button>
              )}
              <button onClick={fetchLeads} disabled={loading} className="bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded-lg">
                {t.actions.refresh}
              </button>
              
              {statusFilter !== 'all' && (
                <span className="text-sm text-gray-400">
                  {t.filters.filterByStatus}: <strong>{t.status[statusFilter] || statusFilter}</strong>
                  <button onClick={() => setStatusFilter('all')} className="ml-2 text-blue-400 hover:underline">
                    ({t.filters.all})
                  </button>
                </span>
              )}
            </div>
            
            {/* Lead Form Modal */}
            {showForm && (
              <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
                <div className="bg-gray-800 rounded-xl p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto">
                  <h2 className="text-xl font-bold mb-4">{editingLead ? t.form.editLead : t.form.newLead}</h2>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {/* Nome */}
                    <div className="md:col-span-2">
                      <label className="block text-sm text-gray-400 mb-1">{t.form.name} *</label>
                      <input type="text" value={formData.name} onChange={(e) => setFormData({...formData, name: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2" placeholder="John Smith" />
                    </div>
                    
                    {/* Telefone */}
                    <div>
                      <label className="block text-sm text-gray-400 mb-1">{t.form.phone} *</label>
                      <div className="flex gap-2">
                        <select value={phoneCountry} onChange={(e) => setPhoneCountry(e.target.value)}
                          className="bg-gray-700 border border-gray-600 rounded px-2 py-2 w-24">
                          <option value="us">🇺🇸 +1</option>
                          <option value="br">🇧🇷 +55</option>
                        </select>
                        <input type="tel" value={formData.phone} onChange={(e) => setFormData({...formData, phone: e.target.value.replace(/\D/g, '')})}
                          className="flex-1 bg-gray-700 border border-gray-600 rounded px-3 py-2"
                          placeholder={phoneCountry === 'us' ? '3055551234' : '11999999999'} />
                      </div>
                    </div>
                    
                    {/* Email */}
                    <div>
                      <label className="block text-sm text-gray-400 mb-1">{t.form.email}</label>
                      <input type="email" value={formData.email} onChange={(e) => setFormData({...formData, email: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2" placeholder="john@email.com" />
                    </div>
                    
                    {/* ===== ENDEREÇO ===== */}
                    <div className="md:col-span-2 border-t border-gray-700 pt-4 mt-2">
                      <h3 className="text-sm font-medium text-gray-300 mb-3">📍 {t.form.address}</h3>
                    </div>
                    
                    <div className="md:col-span-2">
                      <label className="block text-sm text-gray-400 mb-1">{t.form.street}</label>
                      <input type="text" value={formData.street} onChange={(e) => setFormData({...formData, street: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2" placeholder="123 Main Street" />
                    </div>
                    
                    <div>
                      <label className="block text-sm text-gray-400 mb-1">{t.form.city}</label>
                      <input type="text" value={formData.city} onChange={(e) => setFormData({...formData, city: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2" placeholder="Miami" />
                    </div>
                    
                    <div className="flex gap-2">
                      <div className="flex-1">
                        <label className="block text-sm text-gray-400 mb-1">{t.form.state}</label>
                        <select value={formData.state} onChange={(e) => setFormData({...formData, state: e.target.value})}
                          className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2">
                          <option value="">--</option>
                          {US_STATES.map(st => <option key={st} value={st}>{st}</option>)}
                        </select>
                      </div>
                      <div className="flex-1">
                        <label className="block text-sm text-gray-400 mb-1">{t.form.zipCode}</label>
                        <input type="text" value={formData.zipCode} onChange={(e) => setFormData({...formData, zipCode: e.target.value.replace(/\D/g, '').substring(0,5)})}
                          className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2" placeholder="33101" maxLength={5} />
                      </div>
                    </div>
                    
                    {/* ===== CHAVEAMENTOS DE IDIOMA ===== */}
                    <div className="md:col-span-2 border-t border-gray-700 pt-4 mt-2">
                      <h3 className="text-sm font-medium text-gray-300 mb-3">🌐 {systemLang === 'pt' ? 'Configuração de Idiomas' : 'Language Settings'}</h3>
                    </div>
                    
                    <div>
                      <label className="block text-sm text-gray-400 mb-1">📜 {t.form.promptLang} *</label>
                      <select value={formData.promptLang} onChange={(e) => setFormData({...formData, promptLang: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2">
                        <option value="en">{t.languages.en}</option>
                        <option value="es">{t.languages.es}</option>
                        <option value="pt">{t.languages.pt}</option>
                      </select>
                      <p className="text-xs text-gray-500 mt-1">{t.form.promptLangHelp}</p>
                    </div>
                    
                    <div>
                      <label className="block text-sm text-gray-400 mb-1">🗣️ {t.form.language} *</label>
                      <select value={formData.language} onChange={(e) => setFormData({...formData, language: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2">
                        <option value="en">{t.languages.en}</option>
                        <option value="es">{t.languages.es}</option>
                        <option value="pt">{t.languages.pt}</option>
                      </select>
                      <p className="text-xs text-gray-500 mt-1">{t.form.languageHelp}</p>
                    </div>
                    
                    {/* ===== OBJETIVO ===== */}
                    <div className="md:col-span-2 border-t border-gray-700 pt-4 mt-2">
                      <h3 className="text-sm font-medium text-gray-300 mb-3">🎯 {t.form.objective}</h3>
                    </div>
                    
                    <div className="md:col-span-2">
                      <select value={formData.objectiveId} onChange={(e) => setFormData({...formData, objectiveId: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2">
                        <option value="">{t.form.selectObjective}</option>
                        {objectives.map(obj => (
                          <option key={obj.id} value={obj.id}>{obj.name}</option>
                        ))}
                      </select>
                      {objectives.length === 0 && (
                        <p className="text-xs text-yellow-400 mt-1">
                          {systemLang === 'pt' ? '⚠️ Crie objetivos na aba "Objetivos" primeiro.' : '⚠️ Create objectives in the "Objectives" tab first.'}
                        </p>
                      )}
                    </div>
                    
                    {/* ===== RESUMO DA IA ===== */}
                    <div className="md:col-span-2 border-t border-gray-700 pt-4 mt-2">
                      <label className="block text-sm text-gray-400 mb-1">🤖 {t.form.aiSummary}</label>
                      <textarea value={formData.aiSummary} onChange={(e) => setFormData({...formData, aiSummary: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2" rows={2}
                        placeholder={systemLang === 'pt' ? 'Resumo gerado pela IA após a ligação...' : 'Summary generated by AI after the call...'} />
                      <p className="text-xs text-gray-500 mt-1">{t.form.aiSummaryHelp}</p>
                    </div>
                    
                    {/* Notas */}
                    <div className="md:col-span-2">
                      <label className="block text-sm text-gray-400 mb-1">{t.form.notes}</label>
                      <textarea value={formData.notes} onChange={(e) => setFormData({...formData, notes: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2" rows={2} />
                    </div>
                  </div>
                  
                  <div className="flex gap-3 mt-6">
                    <button onClick={closeForm} className="flex-1 bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded-lg">{t.form.cancel}</button>
                    <button onClick={handleSaveLead} disabled={loading || !formData.name || !formData.phone}
                      className="flex-1 bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg disabled:opacity-50">
                      {loading ? t.form.saving : t.form.save}
                    </button>
                  </div>
                </div>
              </div>
            )}
            
            {/* Add Contact Modal */}
            {showContactForm && contactFormLead && (
              <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
                <div className="bg-gray-800 rounded-xl p-6 w-full max-w-md">
                  <h2 className="text-xl font-bold mb-4">{t.contact.addTitle}</h2>
                  <p className="text-gray-400 mb-4">{contactFormLead.name}</p>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm text-gray-400 mb-1">{t.contact.date}</label>
                      <input type="datetime-local" value={contactData.date} onChange={(e) => setContactData({...contactData, date: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2" />
                    </div>
                    <div>
                      <label className="block text-sm text-gray-400 mb-1">{t.contact.outcome}</label>
                      <select value={contactData.outcome} onChange={(e) => setContactData({...contactData, outcome: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2">
                        {Object.entries(t.contact.outcomes).map(([key, label]) => (
                          <option key={key} value={key}>{label}</option>
                        ))}
                      </select>
                    </div>
                    <div>
                      <label className="block text-sm text-gray-400 mb-1">{t.contact.summary}</label>
                      <textarea value={contactData.summary} onChange={(e) => setContactData({...contactData, summary: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2" rows={3} />
                    </div>
                  </div>
                  
                  <div className="flex gap-3 mt-6">
                    <button onClick={() => { setShowContactForm(false); setContactFormLead(null); }}
                      className="flex-1 bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded-lg">{t.form.cancel}</button>
                    <button onClick={handleAddContact} disabled={loading || !contactData.summary}
                      className="flex-1 bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg disabled:opacity-50">{t.form.save}</button>
                  </div>
                </div>
              </div>
            )}
            
            {/* Leads Table */}
            <div className="bg-gray-800 rounded-xl overflow-hidden overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-700">
                  <tr>
                    <th className="p-3 text-left w-10">
                      <input type="checkbox" checked={selectedLeads.size === filteredLeads.length && filteredLeads.length > 0}
                        onChange={toggleSelectAll} className="w-4 h-4" />
                    </th>
                    <th className="p-3 text-left">{t.table.name}</th>
                    <th className="p-3 text-left hidden sm:table-cell">{t.table.phone}</th>
                    <th className="p-3 text-left hidden md:table-cell">{t.table.objective}</th>
                    <th className="p-3 text-left">{t.table.status}</th>
                    <th className="p-3 text-left hidden lg:table-cell">{t.table.summary}</th>
                    <th className="p-3 text-left hidden md:table-cell">{t.table.contacts}</th>
                    <th className="p-3 text-right">{t.table.actions}</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredLeads.map(lead => (
                    <tr key={lead.id} className="border-t border-gray-700 hover:bg-gray-750">
                      <td className="p-3">
                        <input type="checkbox" checked={selectedLeads.has(lead.id)} onChange={() => toggleSelectLead(lead.id)} className="w-4 h-4" />
                      </td>
                      <td className="p-3">
                        <div className="font-medium">{lead.name || '(no name)'}</div>
                        <div className="text-xs text-gray-500">
                          📜 {t.languages[lead.promptLang]?.split(' ')[0] || '🇺🇸'} → 🗣️ {t.languages[lead.language]?.split(' ')[0] || '🇺🇸'}
                        </div>
                      </td>
                      <td className="p-3 font-mono text-sm hidden sm:table-cell">{lead.phone}</td>
                      <td className="p-3 hidden md:table-cell">
                        <span className="text-sm text-cyan-400">{lead.objectiveName || '-'}</span>
                      </td>
                      <td className="p-3">
                        <select 
                          value={lead.status || 'new'} 
                          onChange={(e) => handleQuickStatusChange(lead.id, e.target.value)}
                          className={`text-xs rounded px-2 py-1 border-0 cursor-pointer ${getStatusColor(lead.status || 'new')}`}
                        >
                          {Object.entries(t.status).map(([key, label]) => (
                            <option key={key} value={key} className="bg-gray-800">{label}</option>
                          ))}
                        </select>
                        {lead.lastIntent && lead.lastIntent !== 'unknown' && (
                          <span className={`ml-1 px-2 py-1 rounded text-xs ${getIntentColor(lead.lastIntent)}`}>
                            {lead.lastIntent}
                          </span>
                        )}
                      </td>
                      <td className="p-3 hidden lg:table-cell">
                        {lead.aiSummary ? (
                          <span className="text-sm text-gray-400" title={lead.aiSummary}>
                            {lead.aiSummary.substring(0, 40)}{lead.aiSummary.length > 40 ? '...' : ''}
                          </span>
                        ) : '-'}
                      </td>
                      <td className="p-3 hidden md:table-cell text-center">{lead.totalCalls || 0}</td>
                      <td className="p-3">
                        <div className="flex gap-1 justify-end flex-wrap">
                          <button onClick={() => handleCallSingle(lead)} disabled={loading}
                            className="bg-green-600 hover:bg-green-700 px-2 py-1 rounded text-sm" title={t.actions.call}>📞</button>
                          <button onClick={() => handleViewHistory(lead)}
                            className="bg-purple-600 hover:bg-purple-700 px-2 py-1 rounded text-sm" title={t.actions.viewHistory}>📋</button>
                          <button onClick={() => { setContactFormLead(lead); setShowContactForm(true); }}
                            className="bg-cyan-600 hover:bg-cyan-700 px-2 py-1 rounded text-sm" title={t.actions.addContact}>+</button>
                          <button onClick={() => handleEditLead(lead)}
                            className="bg-blue-600 hover:bg-blue-700 px-2 py-1 rounded text-sm" title={t.actions.edit}>✏️</button>
                          <button onClick={() => handleDeleteLead(lead.id)}
                            className="bg-red-600 hover:bg-red-700 px-2 py-1 rounded text-sm" title={t.actions.delete}>🗑️</button>
                        </div>
                      </td>
                    </tr>
                  ))}
                  {filteredLeads.length === 0 && (
                    <tr><td colSpan={8} className="p-8 text-center text-gray-400">{t.noLeads}</td></tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}
        
        {/* ==================== OBJECTIVES TAB ==================== */}
        {activeTab === 'objectives' && (
          <div className="max-w-4xl">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-xl font-bold">{t.objectives.title}</h2>
              <button onClick={() => { setShowObjectiveForm(true); setEditingObjective(null); setObjectiveFormData({ name: '', description: '' }); }} 
                className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg font-medium">
                {t.objectives.newObjective}
              </button>
            </div>
            
            <p className="text-gray-400 text-sm mb-6">{t.objectives.examples}</p>
            
            {/* Objective Form Modal */}
            {showObjectiveForm && (
              <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
                <div className="bg-gray-800 rounded-xl p-6 w-full max-w-lg">
                  <h2 className="text-xl font-bold mb-4">
                    {editingObjective ? t.objectives.editObjective : t.objectives.newObjective}
                  </h2>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm text-gray-400 mb-1">{t.objectives.name} *</label>
                      <input type="text" value={objectiveFormData.name} onChange={(e) => setObjectiveFormData({...objectiveFormData, name: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2" 
                        placeholder={systemLang === 'pt' ? 'Ex: Levantamento de Necessidade' : 'Ex: Needs Assessment'} />
                    </div>
                    <div>
                      <label className="block text-sm text-gray-400 mb-1">{t.objectives.description} *</label>
                      <textarea value={objectiveFormData.description} onChange={(e) => setObjectiveFormData({...objectiveFormData, description: e.target.value})}
                        className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2" rows={5}
                        placeholder={systemLang === 'pt' 
                          ? 'Ex: Este é o primeiro contato. Descubra se o cliente tem interesse em instalar uma piscina, qual o tamanho do terreno e orçamento disponível.'
                          : 'Ex: This is the first contact. Find out if customer is interested in pool installation, property size and available budget.'} />
                      <p className="text-xs text-gray-500 mt-1">{t.objectives.descriptionHelp}</p>
                    </div>
                  </div>
                  
                  <div className="flex gap-3 mt-6">
                    <button onClick={closeObjectiveForm}
                      className="flex-1 bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded-lg">{t.form.cancel}</button>
                    <button onClick={handleSaveObjective} disabled={!objectiveFormData.name || !objectiveFormData.description}
                      className="flex-1 bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg disabled:opacity-50">{t.form.save}</button>
                  </div>
                </div>
              </div>
            )}
            
            {/* Objectives List */}
            <div className="space-y-4">
              {objectives.map(obj => (
                <div key={obj.id} className="bg-gray-800 rounded-xl p-4">
                  <div className="flex justify-between items-start">
                    <div className="flex-1">
                      <h3 className="font-bold text-lg text-cyan-400">🎯 {obj.name}</h3>
                      <p className="text-gray-400 mt-2 text-sm whitespace-pre-wrap">{obj.description}</p>
                    </div>
                    <div className="flex gap-2 ml-4">
                      <button onClick={() => handleEditObjective(obj)}
                        className="bg-blue-600 hover:bg-blue-700 px-2 py-1 rounded text-sm">✏️</button>
                      <button onClick={() => handleDeleteObjective(obj.id)}
                        className="bg-red-600 hover:bg-red-700 px-2 py-1 rounded text-sm">🗑️</button>
                    </div>
                  </div>
                </div>
              ))}
              {objectives.length === 0 && (
                <div className="bg-gray-800 rounded-xl p-8 text-center text-gray-400">{t.objectives.noObjectives}</div>
              )}
            </div>
          </div>
        )}
        
        {/* ==================== PROMPTS TAB ==================== */}
        {activeTab === 'prompts' && (
          <div className="max-w-4xl">
            <h2 className="text-xl font-bold mb-4">{t.prompts.title}</h2>
            
            <div className="bg-gray-800 rounded-xl p-6">
              <div className="grid grid-cols-2 gap-4 mb-6">
                <div>
                  <label className="block text-sm text-gray-400 mb-1">{t.prompts.type}</label>
                  <select value={editingPromptType} onChange={(e) => setEditingPromptType(e.target.value)}
                    className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2">
                    <option value="system">{t.prompts.systemPrompt}</option>
                    <option value="greeting">{t.prompts.greeting}</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm text-gray-400 mb-1">{t.prompts.selectLang}</label>
                  <select value={editingPromptLang} onChange={(e) => setEditingPromptLang(e.target.value)}
                    className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2">
                    <option value="en">{t.languages.en}</option>
                    <option value="es">{t.languages.es}</option>
                    <option value="pt">{t.languages.pt}</option>
                  </select>
                </div>
              </div>
              
              <div>
                <textarea value={promptText} onChange={(e) => setPromptText(e.target.value)}
                  className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2 font-mono text-sm" rows={15} />
                {editingPromptType === 'greeting' && (
                  <p className="text-xs text-gray-500 mt-1">{t.prompts.nameVar}</p>
                )}
              </div>
              
              <div className="flex gap-3 mt-6">
                <button onClick={handleSavePrompt} disabled={loading} className="bg-blue-600 hover:bg-blue-700 px-6 py-2 rounded-lg">
                  {t.prompts.save}
                </button>
                <button onClick={fetchPrompts} className="bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded-lg">
                  {t.prompts.reload}
                </button>
              </div>
            </div>
          </div>
        )}
        
        {/* ==================== HISTORY TAB ==================== */}
        {activeTab === 'history' && (
          <div>
            <div className="flex items-center gap-4 mb-4">
              <h2 className="text-xl font-bold">{t.history.title}</h2>
              {selectedLeadForHistory && (
                <span className="bg-blue-600 px-3 py-1 rounded-lg">{selectedLeadForHistory.name}</span>
              )}
            </div>
            
            {!selectedLeadForHistory ? (
              <div className="bg-gray-800 rounded-xl p-8">
                <p className="text-gray-400 mb-4">{t.history.selectLead}</p>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                  {leads.slice(0, 12).map(lead => (
                    <button key={lead.id} onClick={() => handleViewHistory(lead)}
                      className="bg-gray-700 hover:bg-gray-600 p-3 rounded-lg text-left">
                      <div className="font-medium">{lead.name}</div>
                      <div className="text-sm text-gray-400">{lead.phone}</div>
                      <div className="text-xs text-gray-500">{lead.totalCalls || 0} contacts</div>
                    </button>
                  ))}
                </div>
              </div>
            ) : (
              <div className="space-y-4">
                <button onClick={() => setSelectedLeadForHistory(null)} className="text-blue-400 hover:underline text-sm">
                  ← {systemLang === 'pt' ? 'Voltar' : 'Back'}
                </button>
                
                {/* Lead Info */}
                <div className="bg-gray-800 rounded-xl p-4 mb-4">
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                    <div><span className="text-gray-400">📞</span> {selectedLeadForHistory.phone}</div>
                    <div><span className="text-gray-400">📜</span> Prompt: {t.languages[selectedLeadForHistory.promptLang] || 'EN'}</div>
                    <div><span className="text-gray-400">🗣️</span> Speaks: {t.languages[selectedLeadForHistory.language] || 'EN'}</div>
                    <div><span className="text-gray-400">🎯</span> {selectedLeadForHistory.objectiveName || '-'}</div>
                  </div>
                  {selectedLeadForHistory.aiSummary && (
                    <div className="mt-3 p-3 bg-gray-700 rounded">
                      <span className="text-xs text-gray-400">🤖 {t.history.summary}:</span>
                      <p className="text-sm mt-1">{selectedLeadForHistory.aiSummary}</p>
                    </div>
                  )}
                </div>
                
                {leadHistory.map((contact, idx) => (
                  <div key={contact.id || idx} className="bg-gray-800 rounded-xl p-4">
                    <div className="flex justify-between items-start mb-3">
                      <div>
                        <span className={`px-2 py-1 rounded text-xs mr-2 ${contact.contactType === 'manual' ? 'bg-cyan-600' : 'bg-purple-600'}`}>
                          {contact.contactType === 'manual' ? t.history.manual : t.history.aiCall}
                        </span>
                        <span className="text-gray-400 text-sm">{formatDate(contact.startedAt || contact.date)}</span>
                      </div>
                      <div className="text-right">
                        {contact.duration && <div className="text-sm text-gray-400">{t.history.duration}: {contact.duration}s</div>}
                        {contact.intent && contact.intent !== 'unknown' && (
                          <span className={`px-2 py-1 rounded text-xs ${getIntentColor(contact.intent)}`}>{contact.intent}</span>
                        )}
                        {contact.outcome && (
                          <span className="px-2 py-1 rounded text-xs bg-gray-600 ml-1">{getOutcomeLabel(contact.outcome)}</span>
                        )}
                      </div>
                    </div>
                    
                    {contact.callContext && (
                      <div className="bg-yellow-900/30 border border-yellow-700 rounded p-2 mb-3">
                        <span className="text-xs text-yellow-400">🎯 {t.history.context}:</span>
                        <p className="text-sm">{contact.callContext}</p>
                      </div>
                    )}
                    
                    {contact.summary && (
                      <div className="bg-gray-700 rounded p-3 mb-3">
                        <p className="text-sm">{contact.summary}</p>
                      </div>
                    )}
                    
                    {contact.transcript && contact.transcript.length > 0 && (
                      <div className="bg-gray-900 rounded p-3 mt-3">
                        <h4 className="text-sm font-medium text-gray-400 mb-2">{t.history.transcript}:</h4>
                        <div className="space-y-2 max-h-60 overflow-y-auto">
                          {contact.transcript.map((msg, i) => (
                            <div key={i} className={`text-sm ${msg.role === 'assistant' ? 'text-blue-400' : 'text-green-400'}`}>
                              <span className="font-medium">{msg.role === 'assistant' ? '🤖' : '👤'}</span> {msg.text}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
                {leadHistory.length === 0 && (
                  <div className="bg-gray-800 rounded-xl p-8 text-center text-gray-400">{t.history.noHistory}</div>
                )}
              </div>
            )}
          </div>
        )}
        
        {/* ==================== QUEUE TAB ==================== */}
        {activeTab === 'queue' && (
          <div className="max-w-2xl">
            <h2 className="text-xl font-bold mb-4">{t.queue.title}</h2>
            
            {queueStatus ? (
              <div className="space-y-4">
                <div className={`rounded-xl p-6 ${queueStatus.isProcessing ? 'bg-yellow-900/30 border border-yellow-600' : 'bg-gray-800'}`}>
                  <div className="flex justify-between items-center">
                    <div>
                      <h3 className="text-lg font-medium">{queueStatus.isProcessing ? t.queue.inProgress : t.queue.stopped}</h3>
                      {queueStatus.current && (
                        <p className="text-gray-300 mt-1">
                          {t.queue.calling}: <strong>{queueStatus.current.leadName}</strong><br />
                          <span className="text-sm text-gray-400">{queueStatus.current.phone}</span>
                        </p>
                      )}
                    </div>
                    <div className="text-right">
                      <div className="text-3xl font-bold text-blue-400">{queueStatus.pending}</div>
                      <div className="text-sm text-gray-400">{t.queue.pending}</div>
                    </div>
                  </div>
                  {queueStatus.isProcessing && (
                    <button onClick={handleCancelQueue} className="mt-4 bg-red-600 hover:bg-red-700 px-4 py-2 rounded-lg w-full">
                      {t.queue.cancel}
                    </button>
                  )}
                </div>
                
                {queueStatus.results?.length > 0 && (
                  <div className="bg-gray-800 rounded-xl p-4">
                    <h4 className="font-medium mb-3">{t.queue.results} ({queueStatus.completedCount} {t.queue.completed})</h4>
                    <div className="space-y-2">
                      {queueStatus.results.map((r, i) => (
                        <div key={i} className="flex justify-between items-center bg-gray-700 rounded p-2">
                          <span>{r.leadName || r.leadId}</span>
                          <span className={`px-2 py-1 rounded text-xs ${r.status === 'completed' ? 'bg-green-600' : r.status === 'failed' ? 'bg-red-600' : 'bg-gray-600'}`}>
                            {r.status}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className="bg-gray-800 rounded-xl p-8 text-center text-gray-400">Loading...</div>
            )}
          </div>
        )}
        
        {/* ==================== SETTINGS TAB ==================== */}
        {activeTab === 'settings' && (
          <div className="max-w-2xl">
            <h2 className="text-xl font-bold mb-6">{t.settings.title}</h2>
            
            <div className="bg-gray-800 rounded-xl p-6 space-y-6">
              <div>
                <label className="block text-sm text-gray-400 mb-1">🏢 {t.settings.companyName}</label>
                <input type="text" value={companyName} onChange={(e) => setCompanyName(e.target.value)}
                  className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2"
                  placeholder={systemLang === 'pt' ? 'Ex: Pool Solutions' : 'Ex: Pool Solutions'} />
                <p className="text-xs text-gray-500 mt-1">{t.settings.companyNameHelp}</p>
              </div>
              
              <button onClick={handleSaveSettings} disabled={loading} className="bg-blue-600 hover:bg-blue-700 px-6 py-2 rounded-lg">
                {t.form.save}
              </button>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
// ============================================================================
// COMPONENTE PRINCIPAL COM PROTEÇÃO
// ============================================================================

export default function Dashboard() {
  return (
    <ProtectedRoute>
      <DashboardContent />
    </ProtectedRoute>
  );
}